version: '3.8'

services:
  # Redis
  redis:
    image: redis:latest
    container_name: flight-redis
    ports:
      - "6379:6379"

  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: flight-sql
    cap_add:
      - SYS_PTRACE
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Pass123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

volumes:
  sql_data: